"""make timeboxes one to many not many to many

Revision ID: 746cd33f7555
Revises: 94906fa402c0
Create Date: 2022-02-20 19:25:12.167110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746cd33f7555'
down_revision = '94906fa402c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.add_column('task', sa.Column('timebox_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'timebox', ['timebox_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'timebox_id')
    op.create_table('association',
    sa.Column('timebox_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='association_task_id_fkey'),
    sa.ForeignKeyConstraint(['timebox_id'], ['timebox.id'], name='association_timebox_id_fkey')
    )
    # ### end Alembic commands ###
