"""added Goals

Revision ID: 9bfd68b5b2d8
Revises: 746cd33f7555
Create Date: 2022-03-09 07:39:54.749560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfd68b5b2d8'
down_revision = '746cd33f7555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('timebox_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['timebox_id'], ['timebox.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###
