"""users and projects many-to-many

Revision ID: 9e495fc99d69
Revises: bd820067ad4f
Create Date: 2023-02-07 21:09:06.395469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e495fc99d69'
down_revision = 'bd820067ad4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('project_user_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_user_id_fkey', 'project', 'user', ['user_id'], ['id'])
    op.drop_table('user_project')
    # ### end Alembic commands ###
