"""single goal per timebox

Revision ID: bd820067ad4f
Revises: e573ed587d44
Create Date: 2023-02-05 19:01:49.638249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd820067ad4f'
down_revision = 'e573ed587d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timebox', sa.Column('goal', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timebox', 'goal')
    # ### end Alembic commands ###
