"""project type

Revision ID: bf7a0c298e52
Revises: 9e495fc99d69
Create Date: 2023-02-21 21:16:39.293736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7a0c298e52'
down_revision = '9e495fc99d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_type', sa.String(length=32), nullable=True))
    op.execute("UPDATE project SET project_type = 'board' ")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_type')
    # ### end Alembic commands ###
