"""subtask status

Revision ID: d097b614396e
Revises: cea39e5dd096
Create Date: 2022-05-09 10:45:34.963443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd097b614396e'
down_revision = 'cea39e5dd096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('status', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_subtask_status'), 'subtask', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtask_status'), table_name='subtask')
    op.drop_column('subtask', 'status')
    # ### end Alembic commands ###
